language: node_js
node_js:
  - "7"

before_install:
  - npm install github-release-notes -g

script:
  - npm -v

deploy:
  - provider: script
    verbose: true
    github-token: $GREN_GITHUB_TOKEN
    script: bash ./script/changelog.sh
    on:
      all_branches: true
      tags: false