language: node_js
node_js:
  - "7"

before_install:
  - npm install github-release-notes -g

branches:
  only:
    - master

script:
  - gren changelog --override

deploy:
  - provider: releases
    github-token: $GREN_GITHUB_TOKEN
    file: CHANGELOG.md
    skip_cleanup: true
      on:
        tags: true